In [2]:
# 준비 

# colab 드라이브 연결하기 
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# 모듈 불러오기 
import pandas as pd 
import numpy as np 

In [6]:
df = pd.read_csv("/content/drive/MyDrive/프로젝트/멀티캠퍼스/프로젝트1/모델제작용데이터셋(헬스케어).csv")
df.head(2)

성별코드  연령대코드  시도코드  서식코드  진료과목코드  주상병코드  부상병코드  심결가산율
0     2     12    46     0       5     12     12      3
1     2     12    46     0       1      4     13      3

In [4]:
df_day = pd.read_csv("/content/drive/MyDrive/프로젝트/멀티캠퍼스/프로젝트1/df.csv")

In [7]:
# 이전에 전처리 해둔 요일 컬럼 가져오기 
df['요일'] = df_day['요일']
df.head(2)

성별코드  연령대코드  시도코드  서식코드  진료과목코드  주상병코드  부상병코드  심결가산율 요일
0     2     12    46     0       5     12     12      3  월
1     2     12    46     0       1      4     13      3  화

In [8]:
del df_day

In [9]:
def weekday(day) : 
  days = ['월','화','수','목','금','토','일']
  return days.index(day)
df['요일'] = df['요일'].apply(weekday)

In [10]:
df.head(2)

성별코드  연령대코드  시도코드  서식코드  진료과목코드  주상병코드  부상병코드  심결가산율  요일
0     2     12    46     0       5     12     12      3   0
1     2     12    46     0       1      4     13      3   1

In [9]:
# for i in df.columns : 
#   df[i] = df[i].astype("category")
# df.dtypes

성별코드      category
연령대코드     category
시도코드      category
서식코드      category
진료과목코드    category
주상병코드     category
부상병코드     category
심결가산율     category
요일        category
dtype: object

In [ ]:
df.shape

(13178345, 9)

In [11]:
df.rename(columns = {'서식코드' : '입원여부'}, inplace= True)

# 03. 상관성 확인  

In [ ]:
# 성별과 입원여부 
df_cross = pd.crosstab(index=df['성별코드'],columns=df['입원여부'])

# importing the required function
from scipy.stats import chi2_contingency
 
# Performing Chi-sq test
ChiSqResult = chi2_contingency(df_cross)
print('The P-Value of the ChiSq Test is:', ChiSqResult[1])

The P-Value of the ChiSq Test is: 1.4459695826147777e-15


In [ ]:
# 연령과 입원여부 
df_cross = pd.crosstab(index=df['연령대코드'],columns=df['입원여부'])
 
# Performing Chi-sq test
ChiSqResult = chi2_contingency(df_cross)
print('The P-Value of the ChiSq Test is:', ChiSqResult[1])

The P-Value of the ChiSq Test is: 0.0


In [ ]:
# 시도와 입원여부 
df_cross = pd.crosstab(index=df['시도코드'],columns=df['입원여부'])
 
# Performing Chi-sq test
ChiSqResult = chi2_contingency(df_cross)
print('The P-Value of the ChiSq Test is:', ChiSqResult[1])

The P-Value of the ChiSq Test is: 0.0


In [ ]:
# 진료과목코드와 입원여부 
df_cross = pd.crosstab(index=df['진료과목코드'],columns=df['입원여부'])
 
# Performing Chi-sq test
ChiSqResult = chi2_contingency(df_cross)
print('The P-Value of the ChiSq Test is:', ChiSqResult[1])

The P-Value of the ChiSq Test is: 0.0


In [ ]:
# 주상병코드와 입원여부 
df_cross = pd.crosstab(index=df['주상병코드'],columns=df['입원여부'])
 
# Performing Chi-sq test
ChiSqResult = chi2_contingency(df_cross)
print('The P-Value of the ChiSq Test is:', ChiSqResult[1])

The P-Value of the ChiSq Test is: 0.0


In [ ]:
# 부상병코드와 입원여부 
df_cross = pd.crosstab(index=df['부상병코드'],columns=df['입원여부'])
 
# Performing Chi-sq test
ChiSqResult = chi2_contingency(df_cross)
print('The P-Value of the ChiSq Test is:', ChiSqResult[1])

The P-Value of the ChiSq Test is: 0.0


In [ ]:
# 심결가산율과 입원여부 
df_cross = pd.crosstab(index=df['심결가산율'],columns=df['입원여부'])
 
# Performing Chi-sq test
ChiSqResult = chi2_contingency(df_cross)
print('The P-Value of the ChiSq Test is:', ChiSqResult[1])

The P-Value of the ChiSq Test is: 0.0


In [ ]:
# 요일과 입원여부 
df_cross = pd.crosstab(index=df['요일'],columns=df['입원여부'])
 
# Performing Chi-sq test
ChiSqResult = chi2_contingency(df_cross)
print('The P-Value of the ChiSq Test is:', ChiSqResult[1])

The P-Value of the ChiSq Test is: 0.0


# 04. Pre-processing

In [12]:
# undersampling 하기
from collections import Counter
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import RandomUnderSampler

X = df.drop('입원여부', axis = 1)
y = df['입원여부']

# # X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30)
print("Before undersampling: ", Counter(y))

undersample = RandomUnderSampler(sampling_strategy='majority')

# # fit and apply the transform
X_under, y_under = undersample.fit_resample(X, y)
print("After undersampling: ", Counter(y_under))

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


Before undersampling:  Counter({0: 12894383, 1: 283962})


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


After undersampling:  Counter({0: 283962, 1: 283962})


In [13]:
df_under = pd.DataFrame(X_under , columns= X.columns)
df_under.head(2)

성별코드  연령대코드  시도코드  진료과목코드  주상병코드  부상병코드  심결가산율  요일
0     2     18    11       1      8      4      1   4
1     2      4    27       1     10     10      1   2

In [14]:
df_under['입원여부'] = y_under
df_under.head(2)

성별코드  연령대코드  시도코드  진료과목코드  주상병코드  부상병코드  심결가산율  요일  입원여부
0     2     18    11       1      8      4      1   4     0
1     2      4    27       1     10     10      1   2     0

In [ ]:
# 상관성 재확인 
for i in df_under.columns[:-1] : 
  df_cross = pd.crosstab(index=df_under[i],columns=df_under['입원여부'])
  ChiSqResult = chi2_contingency(df_cross)
  print(f'{i} : The P-Value of the ChiSq Test is:', ChiSqResult[1])

In [15]:
# 데이터 타입 변경 
for i in df.columns : 
  df_under[i] = df[i].astype("category")
df_under.dtypes

성별코드      category
연령대코드     category
시도코드      category
진료과목코드    category
주상병코드     category
부상병코드     category
심결가산율     category
요일        category
입원여부      category
dtype: object

In [47]:
# y 원핫인코딩 
df_under = pd.get_dummies(df_under, columns=['입원여부'])
df_under.head(2)

성별코드 연령대코드 시도코드 진료과목코드 주상병코드 부상병코드 심결가산율 요일  입원여부_0  입원여부_1
0    2    12   46      5    12    12     3  0       1       0
1    2    12   46      1     4    13     3  1       1       0

In [48]:
df_under.rename(columns = {'입원여부_0' : '입원함', '입원여부_1' : '입원안함'}, inplace= True)
df_under.head(2)

성별코드 연령대코드 시도코드 진료과목코드 주상병코드 부상병코드 심결가산율 요일  입원함  입원안함
0    2    12   46      5    12    12     3  0    1     0
1    2    12   46      1     4    13     3  1    1     0

In [49]:
# train, test split 
X = df_under.drop(['입원함', '입원안함'], axis = 1)
y = df_under[['입원함', '입원안함']]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30)

# 05. Model

## 5-1) Decision Tree

In [ ]:
# from sklearn.tree import DecisionTreeClassifier
# tree = DecisionTreeClassifier(criterion = "entropy",max_depth=5)
# tree.fit(X_train,y_train)

# print(tree.score(X_test,y_test))

0.9797098216905938


In [ ]:
# from sklearn.tree import export_graphviz

# export_graphviz(
#     tree, # 학습한 모형
#     out_file = 'tree.dot', # .dot 파일 저장 위치
#     feature_names = list(X.columns), # 사용한 변수 이름
#     class_names = ['입원함', '입원안함'], # 예측할 타겟 클래스 이름
# )
# import graphviz

# # 위에서 생성된 tree.dot 파일을 Graphviz 읽어서 Jupyter Notebook상에서 시각화 
# with open("tree.dot") as f:
#     dot_graph = f.read()
# graphviz.Source(dot_graph)

In [41]:
# X = df_under.drop('입원여부', axis = 1)
# y = df_under['입원여부']

In [ ]:
# # https://www.kaggle.com/gizemtanriver/multi-class-classification-by-decision-tree

# from sklearn.preprocessing import LabelEncoder
# labelencoder_X = LabelEncoder()
# X_encoder=  labelencoder_X.fit_transform(X[:,1])

In [37]:
# y_encoder, class_names= pd.factorize(y.values)

In [57]:
# 데이터셋 분리 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_under, y_under, test_size = 0.25, stratify=y, random_state = 42)

In [58]:
# 모델 생성 
from sklearn.tree import DecisionTreeClassifier
tree2 = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                               max_depth=6, min_samples_leaf=200)
tree2.fit(X_train,y_train)

print(tree2.score(X_test,y_test))


0.8478317521358492


In [ ]:
from sklearn.tree import export_graphviz

export_graphviz(
    tree2, # 학습한 모형
    out_file = 'tree2.dot', # .dot 파일 저장 위치
    feature_names = list(X.columns), # 사용한 변수 이름
    class_names = ['입원함', '입원안함'], # 예측할 타겟 클래스 이름
)
import graphviz

# 위에서 생성된 tree.dot 파일을 Graphviz 읽어서 Jupyter Notebook상에서 시각화 
with open("tree2.dot") as f:
    dot_graph = f.read()
graphviz.Source(dot_graph)

In [76]:
# depth 변화 
score = []
for i in range(3,20) : 
  tree2 = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                               max_depth=i, min_samples_leaf=200)
  tree2.fit(X_train,y_train)
  score.append(tree2.score(X_test,y_test))
print(score)

[0.8451553376860285, 0.8451553376860285, 0.8460498235679422, 0.8478317521358492, 0.8486135468830337, 0.8494376008057416, 0.8502616547284496, 0.8528465076313028, 0.8530718899007613, 0.8556990019791381, 0.8564948831181637, 0.8572555482775864, 0.8576992696205831, 0.8579880406533269, 0.8581077749839767, 0.8582063797268649, 0.8582415957064677]


In [77]:
import plotly.graph_objs as go 
import plotly.express as px

fig = go.Figure()
x = [i for i in range(3,20)]
fig.add_trace(go.Scatter(x = x, y = score))
fig.show()

In [80]:
# depth 12로 모델 생성 
tree2 = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                               max_depth=12, min_samples_leaf=200)
tree2.fit(X_train,y_train)
score.append(tree2.score(X_test,y_test))

In [81]:
# 혼동 행렬 
y_pred_train =tree2.predict(X_train)

from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report

accuracy = metrics.accuracy_score(y_train, y_pred_train)
print("Accuracy: {:.2f}".format(accuracy))
cm=confusion_matrix(y_train,y_pred_train)
print('Confusion Matrix: \n', cm)
# print(classification_report(y_train, y_pred_train, target_names=class_names))

Accuracy: 0.86
Confusion Matrix: 
 [[171848  41128]
 [ 19808 193159]]


In [82]:
# kflod 모델 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

kfold = KFold(n_splits = 6, shuffle = True, random_state = 100)

print("cross validation score : {}".format(cross_val_score(tree2, X_under, y_under, cv = kfold)))

cross validation score : [0.85726963 0.85581169 0.85712173 0.85844233 0.85654066 0.85906565]


## 5-2) Naive Bayes

In [83]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
y_pred = nb.fit(X_train, y_train).predict(X_test)

print("Number of mislabeled points out of a total %d proints : %d" % (X_test.shape[0], (y_test != y_pred).sum()))


Number of mislabeled points out of a total 141981 proints : 33268


In [84]:
nb.score(X_train, y_train)


0.7664898824490601

In [85]:
nb.score(X_test, y_test)

0.7656869581141139

In [86]:
y_pred_train =nb.predict(X_train)

accuracy = metrics.accuracy_score(y_train, y_pred_train)
print("Accuracy: {:.2f}".format(accuracy))
cm=confusion_matrix(y_train,y_pred_train)
print('Confusion Matrix: \n', cm)

Accuracy: 0.77
Confusion Matrix: 
 [[173151  39825]
 [ 59637 153330]]


In [87]:
kfold = KFold(n_splits = 6, shuffle = True, random_state = 100)

print("cross validation score : {}".format(cross_val_score(nb, X_under, y_under, cv = kfold)))

cross validation score : [0.76489108 0.7653348  0.76581021 0.76768018 0.7674055  0.76525028]


## 5-3) Logistic Regression 

In [88]:
from sklearn.linear_model import LogisticRegression

logi = LogisticRegression()
logi.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [91]:
logi.score(X_test,y_test)

0.7972756918179194

In [93]:
logi.coef_

array([[ 0.07475881,  0.05645716,  0.0104982 ,  0.03958719, -0.01199788,
         0.03456582,  1.39462976,  0.06777658]])

In [95]:
y_pred_train =logi.predict(X_train)


accuracy = metrics.accuracy_score(y_train, y_pred_train)
print("Accuracy: {:.2f}".format(accuracy))
cm=confusion_matrix(y_train,y_pred_train)
print('Confusion Matrix: \n', cm)

Accuracy: 0.80
Confusion Matrix: 
 [[173807  39169]
 [ 47195 165772]]


In [96]:
kfold = KFold(n_splits = 6, shuffle = True, random_state = 100)

print("cross validation score : {}".format(cross_val_score(logi, X_under, y_under, cv = kfold)))

cross validation score : [0.79670167 0.79631077 0.79670167 0.79808566 0.79645868 0.79562406]


## 5-4 Knn

In [97]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)

In [98]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [99]:
knn.score(X_test,y_test)

0.8279417668561286

In [100]:
y_pred_train =knn.predict(X_train)


accuracy = metrics.accuracy_score(y_train, y_pred_train)
print("Accuracy: {:.2f}".format(accuracy))
cm=confusion_matrix(y_train,y_pred_train)
print('Confusion Matrix: \n', cm)

Accuracy: 0.89
Confusion Matrix: 
 [[188336  24640]
 [ 20318 192649]]


In [101]:
kfold = KFold(n_splits = 6, shuffle = True, random_state = 100)

print("cross validation score : {}".format(cross_val_score(knn, X_under, y_under, cv = kfold)))

cross validation score : [0.82831153 0.82741353 0.82691698 0.82831153 0.82822702 0.82990682]


거리 가중치 knn 