In [49]:
# 필요 패키지 로드
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.font_manager as fonm
from matplotlib import font_manager, rc
mpl.rcParams['axes.unicode_minus'] = False
font_path = 'C:/Windows/Fonts/정직_1.ttf'
font = fonm.FontProperties(fname=font_path).get_name()
rc('font', family=font)
import pandas as pd
import seaborn as sns

In [50]:
# 로지스틱 모델 로드 및 테스트
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import joblib
lr = LogisticRegression()

In [51]:
# 기존에 처리한 데이터 전처리 코드 로드
df = pd.read_csv('C:\\Workspace\\python\\빅데이터 지능형서비스 개발 팀프로젝트(21.9.27~10.6)\\Project-1\\조정범\\Data\\모델제작용데이터셋(헬스케어).csv')
for i in df.columns:
    df[i] = df[i].astype('category')

print(f"전체환자 데이터 수 : {len(df)} / 입원환자 데이터 수 : {len(df[df['서식코드'] == 1])} / 비입원환자 데이터 수 : {len(df[df['서식코드'] == 0])}")

# 출처 : https://g0n1.tistory.com/34
# 클래스 불균형 처리를 해주는 imbalanced-learn를 호출
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

# ros, rus 객체
ros = RandomOverSampler()
rus = RandomUnderSampler()

# Under 샘플링
# Under 샘플링
undersampled_data, undersampled_label = rus.fit_resample(df[['성별코드', '연령대코드', '시도코드', '진료과목코드', '주상병코드', '부상병코드','심결가산율']].copy(), df[['서식코드']].copy())
undersampled_data = pd.DataFrame(undersampled_data, columns =['성별코드', '연령대코드', '시도코드', '진료과목코드', '주상병코드', '부상병코드','심결가산율'])
undersampled_data['서식코드'] = undersampled_label

df_train1 = undersampled_data[['서식코드']].copy() # 테스트로 사용할 컬럼들
def dummy_data(data, columns):
    for column in columns:
        data = pd.concat([data, pd.get_dummies(data[column], prefix = column)], axis=1)
        data = data.drop(column, axis=1)
    return data
dummy_columns = ['서식코드']
df_train1_dummy = dummy_data(undersampled_data, dummy_columns)
print(f"전체환자 데이터 수 : {len(undersampled_data)} / 입원환자 데이터 수 : {len(undersampled_data[undersampled_data['서식코드'] == 1])} / 비입원환자 데이터 수 : {len(undersampled_data[undersampled_data['서식코드'] == 0])}")

# y값 원-핫 인코딩
# 적용
# X = df_train1_dummy.iloc[:, :-2]
# y = df_train1_dummy.iloc[:, 7:]
# 미적용
X = undersampled_data.iloc[:, :-1]
y = undersampled_data.iloc[:, -1:]

# # Over 샘플링
# oversampled_data, oversampled_label = ros.fit_resample(df[['성별코드', '연령대코드', '시도코드', '진료과목코드', '주상병코드', '부상병코드','심결가산율']].copy(), df[['서식코드']].copy())
# oversampled_data = pd.DataFrame(oversampled_data, columns = ['성별코드', '연령대코드', '시도코드', '진료과목코드', '주상병코드', '부상병코드','심결가산율'])
# oversampled_data['서식코드'] = oversampled_label

# df_train1 = oversampled_data[['서식코드']].copy() # 테스트로 사용할 컬럼들
# def dummy_data(data, columns):
#     for column in columns:
#         data = pd.concat([data, pd.get_dummies(data[column], prefix = column)], axis=1)
#         data = data.drop(column, axis=1)
#     return data
# dummy_columns = ['서식코드']
# df_train1_dummy = dummy_data(oversampled_data, dummy_columns)
# print(f"전체환자 데이터 수 : {len(oversampled_data)} / 입원환자 데이터 수 : {len(oversampled_data[oversampled_data['서식코드'] == 1])} / 비입원환자 데이터 수 : {len(oversampled_data[oversampled_data['서식코드'] == 0])}")


# y값 원-핫 인코딩
# 적용
# X = df_train1_dummy.iloc[:, :-2]
# y = df_train1_dummy.iloc[:, 7:]
# # 미적용
# X = oversampled_data.iloc[:, :-1]
# y = oversampled_data.iloc[:, -1:]


전체환자 데이터 수 : 13178345 / 입원환자 데이터 수 : 283962 / 비입원환자 데이터 수 : 12894383
전체환자 데이터 수 : 567924 / 입원환자 데이터 수 : 283962 / 비입원환자 데이터 수 : 283962


In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y, random_state = 7)

In [53]:
# X_train
y_train

서식코드
7891       0
398837     1
461871     1
506387     1
109346     0
...      ...
522482     1
275384     0
293919     1
496550     1
468704     1

[454339 rows x 1 columns]

In [54]:
lr.fit(X_train, list(y_train['서식코드']))

C:\Users\Bestc\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [55]:
lr.predict(X_train)

array([0, 1, 1, ..., 1, 0, 1], dtype=int64)

In [56]:
# 학습데이터에 대한 성능평가
print(confusion_matrix(y_train, lr.predict(X_train)))
print(classification_report(y_train, lr.predict(X_train)))

[[185443  41727]
 [ 50064 177105]]
              precision    recall  f1-score   support

           0       0.79      0.82      0.80    227170
           1       0.81      0.78      0.79    227169

    accuracy                           0.80    454339
   macro avg       0.80      0.80      0.80    454339
weighted avg       0.80      0.80      0.80    454339



In [57]:
# 테스트 데이터에 대한 성능평가
print(confusion_matrix(y_test, lr.predict(X_test)))
print(classification_report(y_test, lr.predict(X_test)))

[[46490 10302]
 [12220 44573]]
              precision    recall  f1-score   support

           0       0.79      0.82      0.81     56792
           1       0.81      0.78      0.80     56793

    accuracy                           0.80    113585
   macro avg       0.80      0.80      0.80    113585
weighted avg       0.80      0.80      0.80    113585



In [58]:
from sklearn.metrics import accuracy_score
y_pred = lr.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))
print(f'Accuracy : {accuracy*100}')

              precision    recall  f1-score   support

           0       0.79      0.82      0.81     56792
           1       0.81      0.78      0.80     56793

    accuracy                           0.80    113585
   macro avg       0.80      0.80      0.80    113585
weighted avg       0.80      0.80      0.80    113585

Accuracy : 80.17167759827441


In [59]:
print(X_train.columns)
print(lr.coef_)
lr.predict_proba(X_test)

Index(['성별코드', '연령대코드', '시도코드', '진료과목코드', '주상병코드', '부상병코드', '심결가산율'], dtype='object')
[[ 0.07942195  0.05633703  0.01084419  0.04173171 -0.01277403  0.03426625
   1.39688221]]


array([[0.05569258, 0.94430742],
       [0.78704889, 0.21295111],
       [0.55198368, 0.44801632],
       ...,
       [0.68205533, 0.31794467],
       [0.20148859, 0.79851141],
       [0.1170026 , 0.8829974 ]])

In [60]:
# 입력시 받아줄 딕셔너리 작성
# 성별 딕셔너리
sex_dict = dict(zip(['남성', '여성'], [1, 2])) 
print(sex_dict)

# 연령대 코드 딕셔너리
age_code_list = ['00~04', '05~09', '10~14', '15~19', '20~24', '25~29', '30~34', '35~39', '40~44', '45~49', '50~54', '55~59', '60~64', 
                 '65~69', '70~74', '75~79', '80~84', '85~89']
age_dict = dict(zip(age_code_list, [i for i in range(1, 19)]))
print(age_dict)

# -------------------- 수정 및 재작성필요 * 데이터 전처리 및 시각화 필드 코드참조하여 수정중 -------------------- 
# 시도코드 딕셔너리 - 사용할 geojson파일과 명칭 일치화 완료
sido_table = pd.read_csv('C:\\Workspace\\python\\빅데이터 지능형서비스 개발 팀프로젝트(21.9.27~10.6)\\Project-1\\조정범\\Data\\시도코드테이블.csv')
sido_dict = dict(zip(sido_table['시도명'], sido_table['시도코드']))
print(sido_dict)

# 서식코드 딕셔너라
# form_code_list = ['청구서', '의과입원', '의과외래', '치과입원', '치과외래', '조산원입원', '보건기관입원', '보건기관외래',
#                   '정신과 낮 병동', '정신과 입원', '정신과 외래', '한방입원', '한방외래', '직접조제', '처방조제', '조산원외래']
# form_dict = dict(zip([_ for _ in range(1, len(form_code_list) - 3)] + [13, 20, 21, 99], form_code_list))
form_dict = dict(zip([0, 1], ['비입원', '입원']))
print(form_dict)

# 진료과목코드 딕셔너리
# 진료과목 코드 활용을 위한 전처리(1) / 파일출처 : 보건의료빅데이터개방시스템 (https://opendata.hira.or.kr/op/opc/selectColumnCodeList.do?pageIndex=8)
df_dsbjt= pd.read_excel('C:\\Workspace\\python\\빅데이터 지능형서비스 개발 팀프로젝트(21.9.27~10.6)\\Project-1\\조정범\\Data\\컬럼정보_코드.xls')
df_dsbjt_train = df_dsbjt[df_dsbjt['코드구분'] == '진료과목코드'].drop(['코드구분', '설명'], axis = 1)
df_dsbjt_train['코드'] = df_dsbjt_train['코드'].apply(lambda x: int(x))  
dsbjt_dict = dict(zip(df_dsbjt_train['명칭'], df_dsbjt_train['코드']))
print(dsbjt_dict)

# # 상병코드 딕셔너리
eng_list = ['A','B','C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
code_dict = dict(zip(eng_list, [i for i in range(len(eng_list))]))
print(code_dict)

# 심결가산율 카테고리화 및 인덱싱
df1 = pd.read_csv('C:\\Workspace\\python\\빅데이터 지능형서비스 개발 팀프로젝트(21.9.27~10.6)\\Project-1\\조정범\\Data\\헬스케어데이터.csv')
rate_list = pd.DataFrame(df1['심결가산율'].value_counts()).index
rate_list = sorted(rate_list)
rate_dict = dict(zip(rate_list, [i for i in range(len(rate_list))]))
print(rate_dict)

{'남성': 1, '여성': 2}
{'00~04': 1, '05~09': 2, '10~14': 3, '15~19': 4, '20~24': 5, '25~29': 6, '30~34': 7, '35~39': 8, '40~44': 9, '45~49': 10, '50~54': 11, '55~59': 12, '60~64': 13, '65~69': 14, '70~74': 15, '75~79': 16, '80~84': 17, '85~89': 18}
{'강원도': 42, '경기도': 41, '경상남도': 48, '경상북도': 47, '광주광역시': 29, '대구광역시': 27, '대전광역시': 30, '부산광역시': 26, '서울특별시': 11, '세종특별자치시': 36, '울산광역시': 31, '인천광역시': 28, '전라남도': 46, '전라북도': 45, '제주특별자치도': 49, '충청남도': 44, '충청북도': 43}
{0: '비입원', 1: '입원'}
{'일반의': 0, '내과': 1, '신경과': 2, '정신건강의학과': 3, '외과': 4, '정형외과': 5, '신경외과': 6, '흉부외과': 7, '성형외과': 8, '마취통증의학과': 9, '산부인과': 10, '소아청소년과': 11, '안과': 12, '이비인후과': 13, '피부과': 14, '비뇨의학과': 15, '영상의학과': 16, '방사선종양학과': 17, '병리과': 18, '진단검사의학과': 19, '결핵과': 20, '재활의학과': 21, '핵의학과': 22, '가정의학과': 23, '응급의학과': 24, '직업환경의학과': 25, '예방의학과': 26, '기타1(치과)': 27, '기타4(한방)': 28, '기타2': 40, '보건': 41, '기타3': 42, '보건기관치과': 43, '보건기관한방': 44, '치과': 49, '구강악안면외과': 50, '치과보철과': 51, '치과교정과': 52, '소아치과': 53, '치주과': 54, '치과보존과': 55, '구강내과': 56, '영

In [61]:
value_list = ['남성', '60~64', '전라남도', '신경외과', 'A', 'D', 0.25]
value_list[0]
input_list = [[sex_dict[value_list[0]]], [age_dict[value_list[1]]], [sido_dict[value_list[2]]], [dsbjt_dict[value_list[3]]], [code_dict[value_list[4]]], \
              [code_dict[value_list[5]]], [rate_dict[value_list[6]]]]
input_list
test = pd.DataFrame(columns = ['성별코드', '연령대코드', '시도코드', '진료과목코드', '주상병코드', '부상병코드', '심결가산율'])
test.shape
for i in range(len(input_list)):
    columns = ['성별코드', '연령대코드', '시도코드', '진료과목코드', '주상병코드', '부상병코드', '심결가산율']
    test[columns[i]] = input_list[i]
test

성별코드  연령대코드  시도코드  진료과목코드  주상병코드  부상병코드  심결가산율
0     1     13    46       6      0      3      3

In [62]:
 y_pred = lr.predict(test)
 f'해당 환자의 {form_dict[y_pred[0]]}확률은 {round(lr.predict_proba(test)[0][1] * 100, 2) if form_dict[y_pred[0]] == "입원" else round(lr.predict_proba(test)[0][0] * 100, 2)}%로 {form_dict[y_pred[0]]}할 것으로 예상됩니다.'

'해당 환자의 입원확률은 82.16%로 입원할 것으로 예상됩니다.'

In [63]:
lr.predict_proba(test)[0][0]

0.17838042025288892

In [64]:
X_val = X_train.copy()
X_val['서식코드'] = y_train.copy()
y_val = X_val.copy().iloc[:, -1:]
X_val = X_val.copy().iloc[:, :-1]
X_val
y_val

서식코드
7891       0
398837     1
461871     1
506387     1
109346     0
...      ...
522482     1
275384     0
293919     1
496550     1
468704     1

[454339 rows x 1 columns]

In [65]:
X_val1, X_val2, y_val1, y_val2 = train_test_split(X_val, y_val, test_size = 0.5, stratify = y_val, random_state = 77)

In [66]:
y_pred1 = lr.predict(X_val1)
accuracy1 = accuracy_score(y_val1, y_pred1)
print(f'Accuracy : {accuracy1*100}')

y_pred2 = lr.predict(X_val2)
accuracy2 = accuracy_score(y_val2, y_pred2)
print(f'Accuracy : {accuracy2*100}')

Accuracy : 79.95148985997209
Accuracy : 79.64211823744333


In [68]:
# kflod 모델 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

kfold = KFold(n_splits = 6, shuffle = True, random_state = 100)

print("cross validation score : {}".format(cross_val_score(lr, X, list(y['서식코드']), cv = kfold)))

cross validation score : [0.79836034 0.79798001 0.79946965 0.79998732 0.79884632 0.798223  ]
