In [40]:
# 필요 패키지 로드
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.font_manager as fonm
from matplotlib import font_manager, rc
mpl.rcParams['axes.unicode_minus'] = False
font_path = 'C:/Windows/Fonts/정직_1.ttf'
font = fonm.FontProperties(fname=font_path).get_name()
rc('font', family=font)
import pandas as pd
import seaborn as sns

In [41]:
# 나이브베이즈드(다항분포) 로드 및 테스트
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import joblib
model = MultinomialNB()

In [42]:
# 기존에 처리한 데이터 전처리 코드 로드
df = pd.read_csv('C:\\Workspace\\python\\빅데이터 지능형서비스 개발 팀프로젝트(21.9.27~10.6)\\Project-1\\조정범\\Data\\모델제작용데이터셋(헬스케어).csv')
for i in df.columns:
    df[i] = df[i].astype('category')

print(f"전체환자 데이터 수 : {len(df)} / 입원환자 데이터 수 : {len(df[df['서식코드'] == 1])} / 비입원환자 데이터 수 : {len(df[df['서식코드'] == 0])}")

# 출처 : https://g0n1.tistory.com/34
# 클래스 불균형 처리를 해주는 imbalanced-learn를 호출
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

# ros, rus 객체
ros = RandomOverSampler()
rus = RandomUnderSampler()

# Under 샘플링
# Under 샘플링
# undersampled_data, undersampled_label = rus.fit_resample(df[['성별코드', '연령대코드', '시도코드', '진료과목코드', '주상병코드', '부상병코드','심결가산율']].copy(), df[['서식코드']].copy())
# undersampled_data = pd.DataFrame(undersampled_data, columns =['성별코드', '연령대코드', '시도코드', '진료과목코드', '주상병코드', '부상병코드','심결가산율'])
# undersampled_data['서식코드'] = undersampled_label

# df_train1 = undersampled_data[['서식코드']].copy() # 테스트로 사용할 컬럼들
# def dummy_data(data, columns):
#     for column in columns:
#         data = pd.concat([data, pd.get_dummies(data[column], prefix = column)], axis=1)
#         data = data.drop(column, axis=1)
#     return data
# dummy_columns = ['서식코드']
# df_train1_dummy = dummy_data(undersampled_data, dummy_columns)
# print(f"전체환자 데이터 수 : {len(undersampled_data)} / 입원환자 데이터 수 : {len(undersampled_data[undersampled_data['서식코드'] == 1])} / 비입원환자 데이터 수 : {len(undersampled_data[undersampled_data['서식코드'] == 0])}")

# y값 원-핫 인코딩
# 적용
# X = df_train1_dummy.iloc[:, :-2]
# y = df_train1_dummy.iloc[:, 7:]
# 미적용
# X = undersampled_data.iloc[:, :-1]
# y = undersampled_data.iloc[:, -1:]

# # Over 샘플링
oversampled_data, oversampled_label = ros.fit_resample(df[['성별코드', '연령대코드', '시도코드', '진료과목코드', '주상병코드', '부상병코드','심결가산율']].copy(), df[['서식코드']].copy())
oversampled_data = pd.DataFrame(oversampled_data, columns = ['성별코드', '연령대코드', '시도코드', '진료과목코드', '주상병코드', '부상병코드','심결가산율'])
oversampled_data['서식코드'] = oversampled_label

df_train1 = oversampled_data[['서식코드']].copy() # 테스트로 사용할 컬럼들
def dummy_data(data, columns):
    for column in columns:
        data = pd.concat([data, pd.get_dummies(data[column], prefix = column)], axis=1)
        data = data.drop(column, axis=1)
    return data
dummy_columns = ['서식코드']
df_train1_dummy = dummy_data(oversampled_data, dummy_columns)
print(f"전체환자 데이터 수 : {len(oversampled_data)} / 입원환자 데이터 수 : {len(oversampled_data[oversampled_data['서식코드'] == 1])} / 비입원환자 데이터 수 : {len(oversampled_data[oversampled_data['서식코드'] == 0])}")


# y값 원-핫 인코딩
# 적용
# X = df_train1_dummy.iloc[:, :-2]
# y = df_train1_dummy.iloc[:, 7:]
# # 미적용
X = oversampled_data.iloc[:, :-1]
y = oversampled_data.iloc[:, -1:]

전체환자 데이터 수 : 13178345 / 입원환자 데이터 수 : 283962 / 비입원환자 데이터 수 : 12894383
전체환자 데이터 수 : 25788766 / 입원환자 데이터 수 : 12894383 / 비입원환자 데이터 수 : 12894383


In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y, random_state = 7)

In [52]:
# X_train
y_train.head(20)

서식코드
25711996     1
19515819     1
19790844     1
18046400     1
19155422     1
16013524     1
9923882      0
7173610      0
5335717      0
4029450      0
9158106      0
17873473     1
9318024      0
24187790     1
17106627     1
12717657     0
23153318     1
13527067     1
1721701      0
13854836     1

In [45]:
# X_train
list(y_train['서식코드'])

[1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,


In [46]:
model.fit(X_train, list(y_train['서식코드']))

MultinomialNB()

In [47]:
# 학습데이터에 대한 성능평가
print(confusion_matrix(y_train, model.predict(X_train)))
print(classification_report(y_train, model.predict(X_train)))

[[6859804 3455702]
 [4182945 6132561]]
              precision    recall  f1-score   support

           0       0.62      0.66      0.64  10315506
           1       0.64      0.59      0.62  10315506

    accuracy                           0.63  20631012
   macro avg       0.63      0.63      0.63  20631012
weighted avg       0.63      0.63      0.63  20631012



In [48]:
# 테스트 데이터에 대한 성능평가
print(confusion_matrix(y_test, model.predict(X_test)))
print(classification_report(y_test, model.predict(X_test)))

[[1714800  864077]
 [1045921 1532956]]
              precision    recall  f1-score   support

           0       0.62      0.66      0.64   2578877
           1       0.64      0.59      0.62   2578877

    accuracy                           0.63   5157754
   macro avg       0.63      0.63      0.63   5157754
weighted avg       0.63      0.63      0.63   5157754



In [49]:
model.predict_proba(X_test)

array([[0.12747734, 0.87252266],
       [0.58082589, 0.41917411],
       [0.87117025, 0.12882975],
       ...,
       [0.40778543, 0.59221457],
       [0.68713913, 0.31286087],
       [0.39023842, 0.60976158]])

In [50]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))
print(f'Accuracy : {accuracy*100}')

              precision    recall  f1-score   support

           0       0.62      0.66      0.64   2578877
           1       0.64      0.59      0.62   2578877

    accuracy                           0.63   5157754
   macro avg       0.63      0.63      0.63   5157754
weighted avg       0.63      0.63      0.63   5157754

Accuracy : 62.96841609739433


In [51]:
# kflod 모델 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

kfold = KFold(n_splits = 6, shuffle = True, random_state = 100)

print("cross validation score : {}".format(cross_val_score(model, X, list(y['서식코드']), cv = kfold)))

cross validation score : [0.62961736 0.62929536 0.63010385 0.63029882 0.62974337 0.62963821]
